### ISSUE TITLE
Breakdown large jsx rendering logic into separate components for better readability

### ISSUE THREAD

**Issue by RakibulRanak** [Monabbir-Ahmmad/Blogify-Frontend#8]
https://github.com/Monabbir-Ahmmad/Blogify-Frontend/blob/6c5bec9315d05ea27331a9b0c1cb8072743b858b/frontend/src/components/nav/Navbar.jsx#LL61C1-L140C1

**Comment by Monabbir-Ahmmad** [comment]
The issues are fixed in the newest release
