### ISSUE TITLE
Make it a one liner by defining two separate components at the top.

### ISSUE THREAD

**Issue by RakibulRanak** [Monabbir-Ahmmad/Blogify-Frontend#9]
https://github.com/Monabbir-Ahmmad/Blogify-Frontend/blob/6c5bec9315d05ea27331a9b0c1cb8072743b858b/frontend/src/components/nav/SideNav.jsx#LL100C2-L120C13

**Comment by Monabbir-Ahmmad** [comment]
The issues are fixed in the newest release.

**Comment by Monabbir-Ahmmad** [comment]
The issues are fixed in the newest release
